# # Seldon Core Operator
# Below are the overrides for kubeflow defaults

# Istio gateway must be set to the kubeflow default
istio:
  enabled: true
  gateway: istio-system/restricted
  tlsMode: ""

# Certmanager using existing cert
certManager:
  enabled: true

# Creation of resources automated as CRD too large for apply
managerCreateResources: true

# Disable CRD in helm charts as manager creates resources
crd:
  create: false

kubeflow: true

